# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sane}
  s.version = "0.16.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roger Pack"]
  s.date = %q{2009-12-18}
  s.description = %q{Helpers for ruby core to make it easier to work with--things that are missing from core but should arguably be there}
  s.email = ["rogerdpack@gmail.com"]
  s.extra_rdoc_files = [
    "ChangeLog",
     "README",
     "TODO"
  ]
  s.files = [
    "ChangeLog",
     "README",
     "Rakefile",
     "VERSION",
     "lib/_dbg.rb",
     "lib/sane.rb",
     "lib/sane/add_regexes.rb",
     "lib/sane/array_ave.rb",
     "lib/sane/bugs.rb",
     "lib/sane/contain.rb",
     "lib/sane/enumerable-extra.rb",
     "lib/sane/file.rb",
     "lib/sane/float.rb",
     "lib/sane/hash_hashes.rb",
     "lib/sane/hash_minus_hash.rb",
     "lib/sane/irb_startup_options.rb",
     "lib/sane/sane_random.rb",
     "sane.gemspec",
     "spec/spec.sane.rb",
     "todo"
  ]
  s.homepage = %q{http://github.com/rogerdpack/sane_ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Helpers for ruby core to make it easier to work with--things that are missing from core but should arguably be there}
  s.test_files = [
    "spec/spec.sane.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdp-require_all>, [">= 0"])
      s.add_runtime_dependency(%q<os>, [">= 0"])
      s.add_runtime_dependency(%q<andand>, [">= 0"])
    else
      s.add_dependency(%q<rdp-require_all>, [">= 0"])
      s.add_dependency(%q<os>, [">= 0"])
      s.add_dependency(%q<andand>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdp-require_all>, [">= 0"])
    s.add_dependency(%q<os>, [">= 0"])
    s.add_dependency(%q<andand>, [">= 0"])
  end
end

